const rejson = {
  durl: "https://class.dabaostudio.xyz",
  zhiri: "",
  cleang: "",
  tomorrow: 0,
  weekly: "",
  subject1: "",
  src1: "",
  subject2: "",
  src2: "",
  subject3: "",
  src3: "",
  subject4: "",
  src4: "",
  subject5: "",
  src5: "",
  subject6: "",
  src6: "",
  subject7: "",
  src7: "",
  subject8: "",
  src8: "",
  subject9: "",
  src9: "",
  subject10: "",
  src10: "",
  subject11: "",
  src11: "",
  subject12: "",
  src12: "",
  subject13: "",
  src13: "",
};
export default rejson;
